
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 13 23:19:57 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NOTIDENTICAL = 31;
  public static final int IDENTICAL = 30;
  public static final int INCREMENT = 23;
  public static final int CONST = 7;
  public static final int LPAREN = 38;
  public static final int SEMI = 36;
  public static final int GREATER = 32;
  public static final int CONTINUE = 16;
  public static final int INTERFACE = 9;
  public static final int LESS = 34;
  public static final int FOR = 14;
  public static final int MINUS = 24;
  public static final int DECREMENT = 25;
  public static final int RPAREN = 39;
  public static final int AND = 20;
  public static final int OR = 21;
  public static final int COMMA = 37;
  public static final int CLASS = 8;
  public static final int DIV = 27;
  public static final int PLUS = 22;
  public static final int LESSEQ = 35;
  public static final int IF = 12;
  public static final int DOT = 19;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int EQUAL = 29;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 26;
  public static final int NUMBER = 44;
  public static final int MOD = 28;
  public static final int IDENT = 45;
  public static final int BREAK = 15;
  public static final int VOID = 6;
  public static final int LBRACE = 40;
  public static final int ELSE = 13;
  public static final int LSQUARE = 42;
  public static final int ENUM = 10;
  public static final int READ = 4;
  public static final int CHARCONST = 46;
  public static final int RSQUARE = 43;
  public static final int RBRACE = 41;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 11;
  public static final int PROG = 2;
  public static final int GREATEREQ = 33;
  public static final int IMPLEMENTS = 18;
  public static final int PRINT = 3;
}

